// Seed de tipos de movimiento (plantillas).
export const tiposSeed = [
  {
    id: 't-clase-efectivo',
    nombre: 'Clase suelta – efectivo',
    sentido: 'ingreso',
    monto_sugerido: 10000,
    medio_pago_id: 'm-efectivo',
    es_plan: true,
    activo: true,
  },
  {
    id: 't-plan-efectivo',
    nombre: 'Plan mensual – efectivo',
    sentido: 'ingreso',
    monto_sugerido: 70000,
    medio_pago_id: 'm-efectivo',
    es_plan: true,
    activo: true,
  },
  {
    id: 't-plan-transferencia',
    nombre: 'Plan mensual – transferencia',
    sentido: 'ingreso',
    monto_sugerido: 80000,
    medio_pago_id: 'm-transf',
    es_plan: true,
    activo: true,
  },
  {
    id: 't-plan-semestral-efectivo',
    nombre: 'Plan semestral – efectivo',
    sentido: 'ingreso',
    monto_sugerido: 350000,
    medio_pago_id: 'm-efectivo',
    es_plan: true,
    activo: true,
  },
  {
    id: 't-plan-semestral-tarjeta',
    nombre: 'Plan semestral – tarjeta (cuotas)',
    sentido: 'ingreso',
    monto_sugerido: 420000,
    medio_pago_id: 'm-transf',
    es_plan: true,
    activo: true,
  },
  {
    id: 't-plan-kids-clase',
    nombre: 'Clase kids',
    sentido: 'ingreso',
    monto_sugerido: 15000,
    medio_pago_id: 'm-transf',
    es_plan: true,
    activo: true,
  },
  {
    id: 't-plan-kids-mensual',
    nombre: 'Plan kids',
    sentido: 'ingreso',
    monto_sugerido: 40000,
    medio_pago_id: 'm-transf',
    es_plan: true,
    activo: true,
  },
  {
    id: 't-bebida',
    nombre: 'Venta de bebida',
    sentido: 'ingreso',
    monto_sugerido: 800,
    medio_pago_id: 'm-efectivo',
    es_plan: false,
    activo: true,
  },
  {
    id: 't-servicios',
    nombre: 'Servicios gimnasio',
    sentido: 'ingreso',
    monto_sugerido: null,
    medio_pago_id: 'm-efectivo',
    es_plan: false,
    activo: true,
  },
  {
    id: 't-merch',
    nombre: 'Venta merch',
    sentido: 'ingreso',
    monto_sugerido: null,
    medio_pago_id: 'm-efectivo',
    es_plan: false,
    activo: true,
  },
  {
    id: 't-otros-ingreso',
    nombre: 'Otros - ingreso',
    sentido: 'ingreso',
    monto_sugerido: null,
    medio_pago_id: 'm-efectivo',
    es_plan: false,
    activo: true,
  },
  {
    id: 't-otros-egreso',
    nombre: 'Otros - egreso',
    sentido: 'egreso',
    monto_sugerido: null,
    medio_pago_id: 'm-efectivo',
    es_plan: false,
    activo: true,
  },
];


